//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendlerTrainingPlanner.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WendlerTrainingPlanner.Domain.DomainResource", typeof(DomainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be null..
        /// </summary>
        public static string ArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be earlier than today..
        /// </summary>
        public static string ArgumentDateCannotBeEarlierThanToday {
            get {
                return ResourceManager.GetString("ArgumentDateCannotBeEarlierThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string ArgumentNotValid {
            get {
                return ResourceManager.GetString("ArgumentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate {0} was not found..
        /// </summary>
        public static string ExceptionMessageAggregateNotFound {
            get {
                return ResourceManager.GetString("ExceptionMessageAggregateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event of type {0} was tried to save from {1} but no id where set on either..
        /// </summary>
        public static string ExceptionMessageAggregateOrEventMissingId {
            get {
                return ResourceManager.GetString("ExceptionMessageAggregateOrEventMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no constructor without paramerters. This can be either public or private..
        /// </summary>
        public static string ExceptionMessageMissingParameterLessConstructorException {
            get {
                return ResourceManager.GetString("ExceptionMessageMissingParameterLessConstructorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of exercises is not valid..
        /// </summary>
        public static string ExercisesIncorrectOrder {
            get {
                return ResourceManager.GetString("ExercisesIncorrectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A superserie cannot have its own superseries..
        /// </summary>
        public static string SuperseriesAccessoryCannotHaveSuperseries {
            get {
                return ResourceManager.GetString("SuperseriesAccessoryCannotHaveSuperseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training max percentage should be greater than 0 and lower or equal to 1..
        /// </summary>
        public static string TrainingMaxPercentageNotValid {
            get {
                return ResourceManager.GetString("TrainingMaxPercentageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor training plan can be defined only for 1 or 2 cycles..
        /// </summary>
        public static string TrainingPlanTemplateAnchorCyclesInvalid {
            get {
                return ResourceManager.GetString("TrainingPlanTemplateAnchorCyclesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of days of training plan template is not defined..
        /// </summary>
        public static string TrainingPlanTemplateDaysNotDefined {
            get {
                return ResourceManager.GetString("TrainingPlanTemplateDaysNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the template with unique identifier {0}, there shoud be no more than {1} training days..
        /// </summary>
        public static string TrainingPlanTemplateDaysNumberNotValid {
            get {
                return ResourceManager.GetString("TrainingPlanTemplateDaysNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader training plan can be defined only for 2 or 3 cycles..
        /// </summary>
        public static string TrainingPlanTemplateLeaderCyclesInvalid {
            get {
                return ResourceManager.GetString("TrainingPlanTemplateLeaderCyclesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of training plan template is unknown..
        /// </summary>
        public static string TrainingPlanTemplateTypeUnknown {
            get {
                return ResourceManager.GetString("TrainingPlanTemplateTypeUnknown", resourceCulture);
            }
        }
    }
}
