//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendlerTrainingPlanner.Application.CQRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralCqrsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralCqrsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WendlerTrainingPlanner.Application.CQRS.Resources.GeneralCqrsResource", typeof(GeneralCqrsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} date has to be set earlier than {ComparisonValue}..
        /// </summary>
        internal static string ErrorMessage_EarlierThan {
            get {
                return ResourceManager.GetString("ErrorMessage_EarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} has to be greater than {ComparisonValue}..
        /// </summary>
        internal static string ErrorMessage_GreaterThan {
            get {
                return ResourceManager.GetString("ErrorMessage_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} can only contain only letters..
        /// </summary>
        internal static string ErrorMessage_InvalidFormatLettersOnly {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFormatLettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} date has to be set later than {ComparisonValue}..
        /// </summary>
        internal static string ErrorMessage_LaterThan {
            get {
                return ResourceManager.GetString("ErrorMessage_LaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} has to be less than or equal to {ComparisonValue}..
        /// </summary>
        internal static string ErrorMessage_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ErrorMessage_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {MaxLength} characters..
        /// </summary>
        internal static string ErrorMessage_MaximumLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should have only unique values..
        /// </summary>
        internal static string ErrorMessage_OrderNumbersUniqueValues {
            get {
                return ResourceManager.GetString("ErrorMessage_OrderNumbersUniqueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required..
        /// </summary>
        internal static string ErrorMessage_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should have only unique days..
        /// </summary>
        internal static string ErrorMessage_TrainingDays_UniqueValues {
            get {
                return ResourceManager.GetString("ErrorMessage_TrainingDays_UniqueValues", resourceCulture);
            }
        }
    }
}
